theme: jekyll-theme-cayman
title: ChordCore
description: Interpret, Progress and Transpose chords
show_downloads: true
github:
  zip_url: https://github.com/chordcore/chordcore.github.io/raw/main/ChordCore-v1.3_win.zip
